platform :ios, '14.0'

target 'iosApp' do
  use_frameworks!

  # KMP shared module
  pod 'shared', :path => '../shared'

  # Firebase native iOS frameworks (required by gitlive)
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |phase|
      next unless phase.respond_to?(:shell_script)
      if phase.shell_script&.include?('gradlew')
        phase.shell_script = <<~SHELL
          export JAVA_HOME=$(/usr/libexec/java_home)
          export PATH="$JAVA_HOME/bin:$PATH"
          #{phase.shell_script}
        SHELL
      end
    end
  end
 installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end